### ISSUE TITLE
マイグレーションに失敗する

### ISSUE THREAD

**Issue by dp42** [pepabo-college/dp42-todo-app#2]
WEB+DB PRESSの通りコマンドを実行すると以下の通りマイグレーションに失敗してしまう。

```
~/D/s/g/p/dp42-todo-app ❯❯❯ bin/rails g migration CreateTasks content:text status:integer{4}                                        ⏎ master
Running via Spring preloader in process 63369
      invoke  active_record
      create    db/migrate/20170605035722_create_tasks.rb
~/D/s/g/p/dp42-todo-app ❯❯❯ bin/rake db:migrate                                                                                     master ◼
Running via Spring preloader in process 63402
== 20170605035722 CreateTasks: migrating ======================================
-- create_table(:tasks)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `integer4' for #<ActiveRecord::ConnectionAdapters::SQLite3::TableDefinition:0x007fc0c215d580>
Did you mean?  integer
/Users/ksato/Dev/src/github.com/pepabo-college/dp42-todo-app/db/migrate/20170605035722_create_tasks.rb:5:in `block in change'
/Users/ksato/Dev/src/github.com/pepabo-college/dp42-todo-app/db/migrate/20170605035722_create_tasks.rb:3:in `change'
-e:1:in `<main>'
NoMethodError: undefined method `integer4' for #<ActiveRecord::ConnectionAdapters::SQLite3::TableDefinition:0x007fc0c215d580>
Did you mean?  integer
/Users/ksato/Dev/src/github.com/pepabo-college/dp42-todo-app/db/migrate/20170605035722_create_tasks.rb:5:in `block in change'
/Users/ksato/Dev/src/github.com/pepabo-college/dp42-todo-app/db/migrate/20170605035722_create_tasks.rb:3:in `change'
-e:1:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

@uduzra さんに質問したところ、`status:integer{4}`がzshだと式展開されるのでクオートが必要とのこと。

**Comment by dp42** [comment]
指摘通りクォートでくくって無事に作成完了

```
~/D/s/g/p/dp42-todo-app ❯❯❯ bin/rails g migration CreateTasks content:text 'status:integer{4}'                                    ⏎ master ◼
Running via Spring preloader in process 63658
      invoke  active_record
      create    db/migrate/20170605040133_create_tasks.rb
~/D/s/g/p/dp42-todo-app ❯❯❯ bin/rake db:migrate                                                                                     master ◼
Running via Spring preloader in process 63693
== 20170605040133 CreateTasks: migrating ======================================
-- create_table(:tasks)
   -> 0.0015s
== 20170605040133 CreateTasks: migrated (0.0017s) =============================
```
